{
	"version": 1592632616,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/pesawat-sheet0.png",
		"images/pesawat-sheet1.png",
		"images/meteor-sheet0.png",
		"images/pelurukita-sheet0.png",
		"images/lawanalien-sheet0.png",
		"images/tiledbackground2.png",
		"images/pelurulawan-sheet0.png",
		"images/objek-sheet0.png",
		"images/meteorbig-sheet0.png",
		"images/meteorsmall-sheet0.png",
		"images/starbig-sheet0.png",
		"images/player-sheet0.png",
		"images/play-sheet0.png",
		"media/mars.m4a",
		"media/mars.ogg",
		"media/warp jingle.m4a",
		"media/warp jingle.ogg",
		"media/soundpeluru.ogg",
		"media/sounddestroy.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}